### ISSUE TITLE
Input/output errors when ctrl-c in the middle of a rreaddir

### ISSUE THREAD

**Issue by lf94** [pfpacket/rust-9p#15]
In my project hackernewsfs, if I `ls` but Ctrl-C before it finishes, v9fs sends a Tflush to my server which causes an error, which causes my whole server to cease function.

I will open a PR to hopefully resolve this.

**Comment by lf94** [comment]
Actually nevermind, looks like my server needs to implement the method!

**Comment by lf94** [comment]
Ok so nevermind, it looks like even with the rflush added, it still causes input/output errors. I'm really not sure why.

**Comment by lf94** [comment]
Hard to say if it's v9fs not responding properly or rust-9p. Additional `ls` do not cause any `rreaddir`, which leads me to believe it's a v9fs bug.

**Comment by lf94** [comment]
I"m going to say it's v9fs not happy with data being returned even after a Rflush is sent.

**Comment by lf94** [comment]
@pfpacket do you have any ideas what else it possibly could be? This isn't ideal because sometimes a walk or read or readdir will take some time to complete, and killing the process is wanted.

**Comment by lf94** [comment]
I think the issue is the following:

```
Treaddir is sent
Tflush is sent
Rreaddir sends dirs but are ignored
Rflush is sent
At this point v9fs sees the last Treaddir as unfinished since dirs were returned but subsequent Treaddir was not sent to finish it.
```

**Comment by lf94** [comment]
It would be useful if we could then send back multiple message on the `rflush`. Then on `rflush` I could send both `Rflush` and `Rreaddir([])`, satisfying everything.

**Comment by pfpacket** [comment]
Could you provide the runtime log with the command like:
`RUST_LOG=rs9p=info cargo run` or `RUST_LOG=rs9p=info ./a.out`

It will show you all the T/R messages sent/received.

**Comment by lf94** [comment]
@pfpacket it's pretty much what I suspected I think.

[out.txt](https://github.com/pfpacket/rust-9p/files/5777390/out.txt)

After the last log line, the program ceases to respond to anything else.

**Comment by lf94** [comment]
Maybe sending "closing" rreaddir and rread messages always after a rflush will solve the problem?

**Comment by lf94** [comment]
@pfpacket I'm going to email the v9fs list to see what they have to say too.

It's been sent.

**Comment by lf94** [comment]
According to the mailing list, the flush mechanism in v9fs is in need of a rewrite.
