### ISSUE TITLE
Error: I/O error: Unsupported protocol: tcp\

### ISSUE THREAD

**Issue by hswick** [pfpacket/rust-9p#4]
Hi! Wanted to say thanks for this. I've been looking around at a lot of different implementations in other languages, and this was the first one I got to work, and also find it understandable.
Following along with the README demo I ran into an error:
```
Error: I/O error: Unsupported protocol: tcp\
```
I'm not sure if its do to my OS (Ubuntu), but your util library wasn't splitting correctly when using this. So I just took the `\` out, and I used single quotes.

```
cargo run --release 'tcp!0.0.0.0!564' ./foobar
```
Worked for me.

**Comment by pfpacket** [comment]
With my environment with zsh the following works fine but not with bash.

```
# echo "tcp\!0.0.0.0\!564"
tcp!0.0.0.0!564
```

As you showed, `'tcp!0.0.0.0!564'` seems better because it works fine with both bash and zsh. I'll fix this.
Thank you for your report!
